### ISSUE TITLE
[1.20.1] Bug Miners working without energy

### ISSUE THREAD

**Issue by BOLTMAGIC** [MtcLeo05/VoidMiners#16]
Hey, im creating a modpack and a lot of players are using your voidminers mod for progression. But there is a bug when inputing FE and then removing it the miner is still working fine.

<img width="329" height="113" alt="Image" src="https://github.com/user-attachments/assets/9a527c09-82f8-4e53-b485-abc07d180427" />

im using the newest version.

a question:

Is is possible to get the envioromental solar panels as a mod? I would love to play with those :)

thank, you and have a nice day!

**Comment by MtcLuna05** [comment]
Seems like I broke the energy container

Also I was asked for the solar panel mod a lot, I might consider it in the future

**Comment by BOLTMAGIC** [comment]
the original mod author of environmental tech released a version for solar panels (1.20.1) buts its buggy and not finished. the first tier is fully funtional but tier2-8 are not working. you can get some inspiration or ideas and maybe you will make a small mod with 2-4 tiers or something.

https://www.curseforge.com/minecraft/mc-mods/environmental-energy-experimental

and of course thank you for all the work!!
have a nice day :)

**Comment by MtcLuna05** [comment]
Should be fixed next version [1.4.7]

Also since they started porting it to 1.20.1 I don't think it's fair to "snipe" them

**Comment by BOLTMAGIC** [comment]
[]()[]()![image.png](https://github.com/user-attachments/assets/e1d341b9-5b95-4737-9faf-51706ffa50ea)

Got a new bug. It's connected to 100% to energy. And the output is empty. 

Thank you

**Comment by MtcLuna05** [comment]
There seems to be something that broke when updating, and some config values where overriden. I can't fix this as the configs are per instance, but you should close the game, delete config and relaunch, and it should be fixed

**Comment by BOLTMAGIC** [comment]
its a new instance. no settings changed. 
https://streamable.com/z105m3

the miner is working once, then its saying miner not working correctly!

Working with version  1.4.6

**Comment by MtcLuna05** [comment]
latest is 1.4.7, try updating to that one?
or did you mean 1.4.6 works, 1.4.7 doesn't?

**Comment by BOLTMAGIC** [comment]
for 1.4.7 its not working and 1.4.6 it works. yes

**Comment by MtcLuna05** [comment]
strange, I'm testing with 1.4.7  and the miner works without ever stopping

**Comment by BOLTMAGIC** [comment]
I made a new video for you:
https://streamable.com/08avc0

I hope this explains the problem.
Its the newest version 1.4.7

**Comment by MtcLuna05** [comment]
Fixed some more stuff. It should be fixed in 1.5.0
To make sure check if the configs are broken (like really small values in energy storage) then break and replace the miner

**Comment by BOLTMAGIC** [comment]
The update works but Its not possible to connect a pipe/ conduit. 🥲

**Comment by BOLTMAGIC** [comment]
Bump

**Comment by MtcLuna05** [comment]
should be fixed in 1.5.1

**Comment by BOLTMAGIC** [comment]
<img width="1083" height="406" alt="Image" src="https://github.com/user-attachments/assets/b4e09882-1df7-4666-8054-b7ee21ae6fd1" />

https://streamable.com/upgfhf

**Comment by MtcLuna05** [comment]
did you replace the miner after updating? also enderio is still not perfect in latest versions, so try using another mod like mekanism / pipez to make sure the problem is the miner

**Comment by BOLTMAGIC** [comment]
I made a new instance and also tried mekanism pipes. still not working

**Comment by BOLTMAGIC** [comment]
I tested it again with a lot of pipes and its not working. I created a new instance and just had VoidMiners 1.5.1, EMI and the mod to test the pipe
Laserio
EnderIO
Mekanism
EvolvedMekansim
Pipez
AE2 pipes
RS
Integrated Tunnels
Xnet
Modular Routers

**Comment by MLDEG** [comment]
I had the same issue with pipe connections but for some reason a reboot fixed the problem on my custom modpack.

I'm on 1.5.1 of Void Miners

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/3d996882-3654-48c1-a87e-bf4a8bf722a2" />

**Comment by BOLTMAGIC** [comment]
You placed the pipe. Reloged and it connected automatically? 
Thank you!

**Comment by MLDEG** [comment]
No, I installed the mod and tested it immediately, and that's when I realized I couldn't connect a pipe to extract anything.
So I closed my pack, checked GitHub for bug reports, and restarted it.
And magically, it worked, lol
So I don't know why it didn't work the first time!

**Comment by BOLTMAGIC** [comment]
So I tested it and its true. The first time its not connecting and the miner is using FE but not generating anything. After a relog its connecting to a pipe and generating ores. Here the video:

https://streamable.com/juydf3

**Comment by MLDEG** [comment]
In reality the first time, where it doesn't connect to any pipe, it generates resources, but we cannot extract them, when we break the miner it drops all the resources.

**Comment by BOLTMAGIC** [comment]
BUMP @MtcLeo05

**Comment by PsyGuy007-sys** [comment]
@MLDEG Fixed in last **pr**
